Extract chart images from manifests

diff --git a/Jenkinsfile.github b/Jenkinsfile.github
--- a/Jenkinsfile.github
+++ b/Jenkinsfile.github
@@ -12,52 +12,58 @@ pipeline {
     }
 
     stages {
+        stage('Setup') {
+            steps {
+                script {
+                    sh """
+                        command -v parallel >/dev/null 2>&1 || {
+                            echo >&2 "error: parallel: command not found"
+                            exit 1
+                        }
+
+                        rm -fr env3
+                        python3 -m venv env3
+                        . env3/bin/activate
+                        python3 -m ensurepip --upgrade
+                        pip install -U pyyaml
+
+                        curl -L -f https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -o env3/bin/yq && chmod +x env3/bin/yq
+                        curl -L -f https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o env3/bin/jq && chmod +x env3/bin/jq
+                        curl -L -f https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz | tar -xvzOf - linux-amd64/helm > env3/bin/helm && chmod +x env3/bin/helm
+
+                        if test -x /home/jenkins/tools/io.snyk.jenkins.tools.SnykInstallation/snyk_latest/snyk-linux; then
+                            ln -s /home/jenkins/tools/io.snyk.jenkins.tools.SnykInstallation/snyk_latest/snyk-linux env3/bin/snyk
+                        else
+                            curl -L -f https://static.snyk.io/cli/latest/snyk-linux -o env3/bin/snyk && chmod +x env3/bin/snyk
+                        fi
+                    """
+                }
+            }
+        }
+
         stage('Validate') {
-            stages {
-                stage('Setup') {
+            parallel {
+                stage('Assets') {
                     steps {
-                        sh "./validate.sh install_tools"
-                        sh "./validate.sh gen_helm_images"
+                        sh "./assets.sh"
                     }
                 }
 
-                stage('Run Validation Scripts') {
-                    parallel {
-                        stage('Assets') {
-                            steps {
-                                sh "./assets.sh"
-                            }
-                        }
-                        stage('Helm') {
-                            steps {
-                                sh "./validate.sh validate_helm"
-                            }
-                        }
+                stage("Charts and Images") {
+                    steps {
+                        sh ". env3/bin/activate && make -C build/images"
+                    }
+                }
 
-                        stage('RPM Index') {
-                            steps {
-                                sh "./validate.sh validate_rpm_index"
-                            }
-                        }
-
-                        stage('Containers') {
-                            steps {
-                                sh "./validate.sh validate_containers"
-                            }
-                        }
-
-                        stage('Helm Versions') {
-                            steps {
-                                sh "./validate.sh validate_manifest_versions"
-                            }
-                        }
-
-                        stage('Helm Images') {
-                            steps {
-                                sh "./validate.sh update_helmrepo"
-                                sh "./validate.sh validate_helm_images"
-                            }
-                        }
+                stage('RPM Index') {
+                    steps {
+                        sh """
+                            ./hack/verify-rpm-index.sh \
+                                rpm/cray/csm/sle-15sp2/index.yaml \
+                                rpm/cray/csm/sle-15sp2-compute/index.yaml \
+                                rpm/cray/csm/sle-15sp3/index.yaml \
+                                rpm/cray/csm/sle-15sp3-compute/index.yaml
+                        """
                     }
                 }
             }
@@ -83,39 +89,6 @@ pipeline {
                     }
                 }
 
-                stage('Setup') {
-                    steps {
-                        script {
-                            slackSend(channel: env.SLACK_CHANNEL_ALERTS, message: "<${env.BUILD_URL}|CSM ${env.RELEASE_VERSION}> - Setting up build environment")
-                            sh "rm -fr dist"
-                            sh """
-                                rm -fr env3
-                                python3 -m venv env3
-                                . env3/bin/activate
-                                python3 -m ensurepip --upgrade
-                                pip install -U pyyaml
-                                if test -x /home/jenkins/tools/io.snyk.jenkins.tools.SnykInstallation/snyk_latest/snyk-linux; then
-                                    ln -s /home/jenkins/tools/io.snyk.jenkins.tools.SnykInstallation/snyk_latest/snyk-linux env3/bin/snyk
-                                else
-                                    curl -L -f https://static.snyk.io/cli/latest/snyk-linux -o env3/bin/snyk && chmod +x env3/bin/snyk
-                                fi
-                            """
-                        }
-                    }
-                    post {
-                        success {
-                            script {
-                                slackSend(channel: env.SLACK_CHANNEL_ALERTS, color: "good", message: "<${env.BUILD_URL}|CSM ${env.RELEASE_VERSION}> - :white_check_mark: Build environment configured")
-                            }
-                        }
-                        unsuccessful {
-                            script {
-                                slackSend(channel: env.SLACK_CHANNEL_ALERTS, color: "danger", message: "<${env.BUILD_URL}|CSM ${env.RELEASE_VERSION}> - :x: Not able to setup build environment")
-                            }
-                        }
-                    }
-                }
-
                 stage('Build') {
                     environment {
                         // See https://githubmemory.com/repo/jenkinsci/snyk-security-scanner-plugin/issues/107
@@ -126,6 +99,8 @@ pipeline {
                             slackSend(channel: env.SLACK_CHANNEL_ALERTS, message: "<${env.BUILD_URL}|CSM ${env.RELEASE_VERSION}> - Running release.sh")
                             sh """
                                 . env3/bin/activate
+                                make -C build/images clean
+                                rm -fr dist
                                 ./release.sh
                             """
                         }
